### PR TITLE
Fixed mismatch in printf types (IDFGH-8883)

### LINKED ISSUE #10303: "hello_world" `printf` formats do not match input (IDFGH-8882)
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### IDF version.

v5.1-dev-2066-g7869f4e151

### Operating System used.

Linux

### How did you build your project?

Command line with idf.py

### If you are using Windows, please specify command line type.

None

### What is the expected behavior?

"hello_world" example compiles without warnings or errors, even when the `-Werror` compile flag is set

### What is the actual behavior?

Compile fails with two errors (see build logs)

### Steps to reproduce.

Compile "hello_world" with `-Werror` compile flag set

### Build or installation Logs.

```plain
error: format '%u' expects argument of type 'unsigned int', but argument 2 has type 'long unsigned int' [-Werror=format=]
   44 |     printf("%uMB %s flash\n", flash_size / (1024 * 1024),
      |             ~^                ~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              |                           |
      |              unsigned int                long unsigned int
      |             %lu

error: format '%d' expects argument of type 'int', but argument 2 has type 'uint32_t' {aka 'long unsigned int'} [-Werror=format=]
   47 |     printf("Minimum free heap size: %d bytes\n", esp_get_minimum_free_heap_size());
      |                                     ~^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |                                         |
      |                                      int                                       uint32_t {aka long unsigned int}
      |                                     %ld
```

### More Information.

 I plan on submitting a pull request to resolve the behavior

### PR DESCRIPTION
**Pull request by gregjesl**
Closes #10303

### CODE REVIEW

**Comment by KaeLL** [comment]
I believe the `<inttypes.h>` formats would be better.

**Comment by gregjesl** [comment]
@KaeLL Updates made 👍

File: examples/get-started/hello_world/main/hello_world_main.c [hunk 1]
```diff
@@ -34,7 +34,7 @@ void app_main(void)
         return;
     }
 
-    printf("%uMB %s flash\n", flash_size / (1024 * 1024),
+    printf("%luMB %s flash\n", flash_size / (uint32_t)(1024 * 1024),
```
Comment (igrr) [inline examples/get-started/hello_world/main/hello_world_main.c:37]:
```suggestion
    printf("%" PRIu32 "MB %s flash\n", flash_size / (uint32_t)(1024 * 1024),
```
(plus `#include <inttypes.h>` at the top of the file)

**Review by igrr — CHANGES_REQUESTED** [review]
Thanks for the PR @gregjesl!

Could you please also remove the following line in the same PR:
https://github.com/espressif/esp-idf/blob/7869f4e151e3ea2a308b991fbb8e9baa4cec313c/examples/get-started/hello_world/main/CMakeLists.txt#L4
and combine your changes into a single commit (using `git rebase -i`).

**Comment by gregjesl** [comment]
@igrr Changes made. I updated a couple other print statements as well, let me know if I over-did it 😄

**Review by igrr — APPROVED** [review]

**Comment by igrr** [comment]
sha=58d64f9a00dea44273004cfecc15f68008571ab3

**Comment by igrr** [comment]
> I updated a couple other print statements as well, let me know if I over-did it 😄

@gregjesl I actually had to revert the changes related to 8- and 16-bit types. This is because newlib-nano (CONFIG_NEWLIB_NANO_FORMAT option) doesn't support 8-bit-specific format specifier produced by PRIu8... (Our internal CI have caught this issue on C2, where CONFIG_NEWLIB_NANO_FORMAT is enabled by default and this example has started failing.)
